version: '3.8'

services:
  nfs-server:
    build:
      context: .
      dockerfile: ./nfs-server/Dockerfile
    container_name: nfs-server
    privileged: true
    ports:
      - "2049:2049"
    volumes:
      - nfs-data:/export/data
      - ./nfs-server/run.sh:/run.sh
    command: "/bin/sh run.sh"

  nfs-client:
    build:
      context: .
      dockerfile: ./nfs-client/Dockerfile
    container_name: nfs-client
    privileged: true
    depends_on:
      - nfs-server
    volumes:
      - ./mnt/nfs-share:/mnt/nfs-share
      - ./nfs-client/mount.sh:/mount.sh
    command: "/bin/sh mount.sh"

volumes:
  nfs-data:
