# Generated by Django 5.1.2 on 2024-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_upload', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
