services:
  python-ssh:
    build: .
    container_name: python-ssh
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt
      - ./start.sh:/start.sh
    networks:
      python-ssh-net:
        ipv4_address: 172.28.1.2
    ports:
      - "2222:22"
      - "8000:8000"
    tty: true
    command: >
      sh -c "python /app/S3App/manage.py migrate && python /app/S3App/manage.py runserver 0.0.0.0:8000"

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_user
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    networks:
      python-ssh-net:

networks:
  python-ssh-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
