version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_user
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
